[tool.poetry]
name = "trying-linear-regression"
version = "1.0.0"
description = "ğŸŒ¬ğŸŒ¬ğŸŒ¬ Pythonã§ç·šå½¢å›å¸°ã‚’å®Ÿè£…ã—ã¦ã¿ã‚‹ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
